wandb_version: 1

input_size:
  desc: null
  value: 9
hidden_size:
  desc: null
  value: 64
output_size:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 24
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 200
name:
  desc: null
  value: MLP_200_24_001
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712200831.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
